/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nagase' at '16/04/19 10:52' with Gradle 2.12
 *
 * @author nagase, @date 16/04/19 10:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
